apiVersion: v1
kind: Service
metadata:
  name: saitesting-service
spec:
  type: NodePort
  selector:
    app: saitesting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # Choose an available port in the range 30000-32767
